### ISSUE TITLE
inconststent indentation detected

### ISSUE THREAD

**Issue by ghost** [acini/autowikibot-py#16] opened 2014-01-27 05:33 UTC
I don't get what I'm doing wrong I've tried EVERYTHING help please!

**Comment by ghost** [comment] 2014-01-27 05:39
And it doesnt bring back to a specific line. Just what os are you using? I just can't get it running

**Comment by acini** [comment] 2014-01-27 07:03
duplicate of https://github.com/acini/autowikibot-py/issues/11

**Closed as completed by acini** 2014-01-27 07:03 UTC
Labels: duplicate, question
