### ISSUE TITLE
Ok I got it working finally.

### ISSUE THREAD

**Issue by ghost** [acini/autowikibot-py#17] opened 2014-01-27 07:36 UTC
The fix was EASY I just had to download PyCharm on Ubuntu and imported autowikibot-py (the folder) and just pressed run. Thank you acini for this it works really well :) Using Python 2.7.3 btw
(you can close this but maybe leave it up in-case anyone is experiencing the same problem??)

**Comment by acini** [comment] 2014-01-27 07:40
I am glad it is working.

**Comment by acini** [comment] 2014-01-27 07:41
duplicate of https://github.com/acini/autowikibot-py/issues/11

**Closed as completed by acini** 2014-01-27 07:40 UTC
Labels: duplicate, question

**Comment by acini** [comment] 2014-01-27 07:43
And oh, please make sure it is scanning only a specific sub or there will be duplicate posts by /u/autowikibot and your bot.

**Comment by ghost** [comment] 2014-01-27 07:46
Yeahh, I was just about to say - my bot is making dupes haha thanks for telling me :) :palm_tree:

**Comment by ghost** [comment] 2014-01-27 07:52
Why does it do that though? Is it a bug?

**Comment by ghost** [comment] 2014-01-27 08:36
Ok I got a bug when trying this in windows:
Traceback (most recent call last):
  File "C:/Users/MYNAME/Desktop/autowikibot-py-master/autowikibot-commenter.py", line 295, in <module>
    lastload = int(float(time.strftime("%s")))
ValueError: Invalid format string

The only way I got it to work on windows was to put a hashtag in front of this WHOLE line of code:

---

#lastload = int(float(time.strftime("%s")))

while True:
  try:
    #comments = r.get_comments("all",limit = 1000)
    #for post in comments:
    for post in praw.helpers.comment_stream(r,'all', limit = None):

```
  ### Dirty timer hack
  #now = int(float(time.strftime("%s")))
  #diff = now - lastload
  #if diff > 899:
#banned_users = r.get_info(thing_id=banned_users_comment).body.split()
#success("BANNED USER LIST RENEWED")
#save_changing_variables()
#lastload = now
```

---

Did I trigger anything bad? How can I fix this problem?
Also how do I only target a specific subreddit?? (to remove doubleposts)
Also will the comment remover remove double posts?
